version: '3'
services:
  backend:
    build:
      ./backend
    networks:
      - web_nw
  frontend:
    build: ./frontend
    volumes:
      - frontend:/app/build
  proxy:
    build:
      ./proxy
    volumes:
      - frontend:/frontend
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    networks:
      - web_nw
  mongodb:
    networks:
      - web_nw
    image: mongo:latest
networks:
  web_nw:
    driver: bridge
volumes:
  frontend: