version: '3'
services:
  backend:
    build:
      ./backend
    networks:
      - web_nw
    restart: on-failure:3
  frontend:
    build: ./frontend
    volumes:
      - frontend:/app/build
    restart: on-failure:3
  proxy:
    build:
      ./proxy
    volumes:
      - frontend:/frontend
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
    networks:
      - web_nw
    restart: on-failure:3
  mongodb:
    networks:
      - web_nw
    image: mongo:latest
    restart: on-failure:3
  backend-tests:
    build:
      ./tests
    command: bash -c "pytest tests/integration_tests.py"
    networks:
      - web_nw
    depends_on:
      - backend
networks:
  web_nw:
    driver: bridge
volumes:
  frontend: